pipeline{
    agent any
    tools{
        maven "3.9.9"
    }
    stages{
        stage('Compile and Clean'){
            steps{
                dir('backend/proj2'){
                    sh 'mvn clean compile'
                }
            }
        }
        // stage('Test'){
        //     steps{
        //         dir('backend/proj2'){
        //             sh 'mvn test'
        //         }
        //     }
        // }
        stage('deploy'){
            steps{
                dir('backend/proj2'){
                    sh 'mvn package'
                }
            }
        }
        stage('Build Docker Image'){
            steps{
                echo 'Building Image'
                dir('backend/proj2'){
                    sh 'ls'
                    sh 'docker build -t hthamdani/jenkins_docker_revp2:${BUILD_NUMBER} .'
                }
                
            }
        }
        stage('Docker Login'){
            steps{
                dir('backend/proj2'){
                    echo 'Logging into Docker'
                    withCredentials([string(credentialsId: 'DockerId', variable: 'Dockerpwd')]){
                    sh "docker login -u hthamdani -p ${Dockerpwd}"
                    }
                }
            }
        }
        stage('Push Docker Image'){
            steps{
                dir('backend/proj2'){
                    echo 'Pushing Image'
                    sh 'docker push hthamdani/jenkins_docker_revp2:${BUILD_NUMBER}'
                }
            }
        }
        stage('Archiving'){
            steps{
                echo 'Archiving'
                archiveArtifacts '**/target/*.jar'
            }
        }
    }
}
