pipeline{
    agent any
    tools{
        maven "3.9.9"
    }
    environment{
        Aws_Access_Key = credentials('Aws_Access_Key')
        Aws_Access_Secret = credentials('Aws_Access_Secret')
    }
    stages{
        stage('Compile and Clean'){
            steps{
                dir('backend/proj2'){
                    sh 'mvn clean compile'
                }
            }
        }
        stage('Test'){
            steps{
                dir('backend/proj2'){
                    sh 'mvn test'
                }
            }
        }
        stage('deploy'){
            steps{
                dir('backend/proj2'){
                    script{
                        sh """mvn package -Dspring.profiles.active=jenkins -Daws.access.keyId=${Aws_Access_Key} -Daws.access.secret=${Aws_Access_Secret}"""
                    }
                }
            }
        }
        stage('Build Docker Image'){
            steps{
                echo 'Building Image'
                dir('backend/proj2'){
                    sh 'ls'
                    sh 'docker build -t brets1488/jenkins_docker_revp2:${BUILD_NUMBER} .'
                }
                
            }
        }
        stage('Docker Login'){
            steps{
                dir('backend/proj2'){
                    echo 'Logging into Docker'
                    withCredentials([string(credentialsId: 'DockerId', variable: 'Dockerpwd')]){
                    sh "docker login -u hthamdani -p ${Dockerpwd}"
                    }
                }
            }
        }
        stage('Push Docker Image'){
            steps{
                dir('backend/proj2'){
                    echo 'Pushing Image'
                    sh 'docker push brets1488/jenkins_docker_revp2:${BUILD_NUMBER}'
                }
            }
        }
        stage('Archiving'){
            steps{
                echo 'Archiving'
                archiveArtifacts '**/target/*.jar'
            }
        }
    }
}
