name: Yarn Build and Tests CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [22.x]

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    # Change directory to where package.json is located
    - name: Install Node.js and dependencies in frontend
      run: |
        cd frontend
        npm install -g yarn
        yarn install --frozen-lockfile
    
    - name: Build Yarn App
      run: |
        cd frontend
        yarn build
    
    - name: Test Yarn App
      run: |
        cd frontend
        yarn testname: Yarn Build and Tests CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [22.x]

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    # Change directory to where package.json is located
    - name: Install Node.js and dependencies in frontend
      run: |
        cd frontend
        npm install -g yarn
        yarn install --frozen-lockfile
    
    - name: Build Yarn App
      run: |
        cd frontend
        yarn build
    
    - name: Test Yarn App
      run: |
        cd frontend
        yarn test
