name: Yarn Build and Tests CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [22.x]

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    # Change directory to where package.json is located
    - name: Change directory to frontend
      run: cd frontend

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'yarn'
        
    # Install dependencies using yarn.lock
    - name: Install dependencies
      run: yarn install --frozen-lockfile
      working-directory: frontend
    
    - name: Build Yarn App
      run: yarn build
      working-directory: frontend
    
    - name: Test Yarn App
      run: yarn test
      working-directory: frontend
